apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tan-dara9280-reactjs-dara-certificate
  namespace: tan-dara9280-reactjs-dara
spec:
  secretName: tan-dara9280-reactjs-dara-secret-tls
  commonName: tan-dara9280-reactjs-dara.assessify.org
  dnsNames:
  - tan-dara9280-reactjs-dara.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
